// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/api/sidecar.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PeerMessage_ConnectRequest
	//	*PeerMessage_ConnectResponse
	//	*PeerMessage_ContainerReport
	Payload       isPeerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessage) Reset() {
	*x = PeerMessage{}
	mi := &file_internal_api_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage) ProtoMessage() {}

func (x *PeerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage.ProtoReflect.Descriptor instead.
func (*PeerMessage) Descriptor() ([]byte, []int) {
	return file_internal_api_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *PeerMessage) GetPayload() isPeerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PeerMessage) GetConnectRequest() *ConnectRequest {
	if x != nil {
		if x, ok := x.Payload.(*PeerMessage_ConnectRequest); ok {
			return x.ConnectRequest
		}
	}
	return nil
}

func (x *PeerMessage) GetConnectResponse() *ConnectResponse {
	if x != nil {
		if x, ok := x.Payload.(*PeerMessage_ConnectResponse); ok {
			return x.ConnectResponse
		}
	}
	return nil
}

func (x *PeerMessage) GetContainerReport() *ContainerReport {
	if x != nil {
		if x, ok := x.Payload.(*PeerMessage_ContainerReport); ok {
			return x.ContainerReport
		}
	}
	return nil
}

type isPeerMessage_Payload interface {
	isPeerMessage_Payload()
}

type PeerMessage_ConnectRequest struct {
	ConnectRequest *ConnectRequest `protobuf:"bytes,1,opt,name=connect_request,json=connectRequest,proto3,oneof"`
}

type PeerMessage_ConnectResponse struct {
	ConnectResponse *ConnectResponse `protobuf:"bytes,2,opt,name=connect_response,json=connectResponse,proto3,oneof"`
}

type PeerMessage_ContainerReport struct {
	ContainerReport *ContainerReport `protobuf:"bytes,3,opt,name=container_report,json=containerReport,proto3,oneof"`
}

func (*PeerMessage_ConnectRequest) isPeerMessage_Payload() {}

func (*PeerMessage_ConnectResponse) isPeerMessage_Payload() {}

func (*PeerMessage_ContainerReport) isPeerMessage_Payload() {}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeHostIp    string                 `protobuf:"bytes,2,opt,name=node_host_ip,json=nodeHostIp,proto3" json:"node_host_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_internal_api_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ConnectRequest) GetNodeHostIp() string {
	if x != nil {
		return x.NodeHostIp
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeHostIp    string                 `protobuf:"bytes,2,opt,name=node_host_ip,json=nodeHostIp,proto3" json:"node_host_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_internal_api_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ConnectResponse) GetNodeHostIp() string {
	if x != nil {
		return x.NodeHostIp
	}
	return ""
}

type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_internal_api_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_internal_api_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerInfo) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ContainerReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerInfo       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerReport) Reset() {
	*x = ContainerReport{}
	mi := &file_internal_api_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerReport) ProtoMessage() {}

func (x *ContainerReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerReport.ProtoReflect.Descriptor instead.
func (*ContainerReport) Descriptor() ([]byte, []int) {
	return file_internal_api_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerReport) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

var File_internal_api_sidecar_proto protoreflect.FileDescriptor

const file_internal_api_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/api/sidecar.proto\x12\asidecar\"\xea\x01\n" +
	"\vPeerMessage\x12B\n" +
	"\x0fconnect_request\x18\x01 \x01(\v2\x17.sidecar.ConnectRequestH\x00R\x0econnectRequest\x12E\n" +
	"\x10connect_response\x18\x02 \x01(\v2\x18.sidecar.ConnectResponseH\x00R\x0fconnectResponse\x12E\n" +
	"\x10container_report\x18\x03 \x01(\v2\x18.sidecar.ContainerReportH\x00R\x0fcontainerReportB\t\n" +
	"\apayload\"O\n" +
	"\x0eConnectRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12 \n" +
	"\fnode_host_ip\x18\x02 \x01(\tR\n" +
	"nodeHostIp\"P\n" +
	"\x0fConnectResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12 \n" +
	"\fnode_host_ip\x18\x02 \x01(\tR\n" +
	"nodeHostIp\"\xbd\x01\n" +
	"\rContainerInfo\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\x06labels\x18\x03 \x03(\v2\".sidecar.ContainerInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x0fContainerReport\x126\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x16.sidecar.ContainerInfoR\n" +
	"containers2K\n" +
	"\x0eSidecarService\x129\n" +
	"\aConnect\x12\x14.sidecar.PeerMessage\x1a\x14.sidecar.PeerMessage(\x010\x01B4Z2github.com/chamoouske/traefik-sidecar/internal/apib\x06proto3"

var (
	file_internal_api_sidecar_proto_rawDescOnce sync.Once
	file_internal_api_sidecar_proto_rawDescData []byte
)

func file_internal_api_sidecar_proto_rawDescGZIP() []byte {
	file_internal_api_sidecar_proto_rawDescOnce.Do(func() {
		file_internal_api_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_sidecar_proto_rawDesc), len(file_internal_api_sidecar_proto_rawDesc)))
	})
	return file_internal_api_sidecar_proto_rawDescData
}

var file_internal_api_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_api_sidecar_proto_goTypes = []any{
	(*PeerMessage)(nil),     // 0: sidecar.PeerMessage
	(*ConnectRequest)(nil),  // 1: sidecar.ConnectRequest
	(*ConnectResponse)(nil), // 2: sidecar.ConnectResponse
	(*ContainerInfo)(nil),   // 3: sidecar.ContainerInfo
	(*ContainerReport)(nil), // 4: sidecar.ContainerReport
	nil,                     // 5: sidecar.ContainerInfo.LabelsEntry
}
var file_internal_api_sidecar_proto_depIdxs = []int32{
	1, // 0: sidecar.PeerMessage.connect_request:type_name -> sidecar.ConnectRequest
	2, // 1: sidecar.PeerMessage.connect_response:type_name -> sidecar.ConnectResponse
	4, // 2: sidecar.PeerMessage.container_report:type_name -> sidecar.ContainerReport
	5, // 3: sidecar.ContainerInfo.labels:type_name -> sidecar.ContainerInfo.LabelsEntry
	3, // 4: sidecar.ContainerReport.containers:type_name -> sidecar.ContainerInfo
	0, // 5: sidecar.SidecarService.Connect:input_type -> sidecar.PeerMessage
	0, // 6: sidecar.SidecarService.Connect:output_type -> sidecar.PeerMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_api_sidecar_proto_init() }
func file_internal_api_sidecar_proto_init() {
	if File_internal_api_sidecar_proto != nil {
		return
	}
	file_internal_api_sidecar_proto_msgTypes[0].OneofWrappers = []any{
		(*PeerMessage_ConnectRequest)(nil),
		(*PeerMessage_ConnectResponse)(nil),
		(*PeerMessage_ContainerReport)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_sidecar_proto_rawDesc), len(file_internal_api_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_sidecar_proto_goTypes,
		DependencyIndexes: file_internal_api_sidecar_proto_depIdxs,
		MessageInfos:      file_internal_api_sidecar_proto_msgTypes,
	}.Build()
	File_internal_api_sidecar_proto = out.File
	file_internal_api_sidecar_proto_goTypes = nil
	file_internal_api_sidecar_proto_depIdxs = nil
}
